// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFN1uy0IcQ8flDOndS2uYWs5cNJZZbkP4',
    appId: '1:748792057873:web:5cf05010467b101a5021b0',
    messagingSenderId: '748792057873',
    projectId: 'propopo-bookshelf',
    authDomain: 'propopo-bookshelf.firebaseapp.com',
    storageBucket: 'propopo-bookshelf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDq8fKcuydX3BLIwLEFE2rE8WKW4LfRo',
    appId: '1:748792057873:android:b643636ad85e39dc5021b0',
    messagingSenderId: '748792057873',
    projectId: 'propopo-bookshelf',
    storageBucket: 'propopo-bookshelf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1mnsryidsO9GUUsJpq_FzuQ5pWvb8AwU',
    appId: '1:748792057873:ios:ea4a98a3b8a402525021b0',
    messagingSenderId: '748792057873',
    projectId: 'propopo-bookshelf',
    storageBucket: 'propopo-bookshelf.firebasestorage.app',
    iosBundleId: 'com.example.bookshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1mnsryidsO9GUUsJpq_FzuQ5pWvb8AwU',
    appId: '1:748792057873:ios:ea4a98a3b8a402525021b0',
    messagingSenderId: '748792057873',
    projectId: 'propopo-bookshelf',
    storageBucket: 'propopo-bookshelf.firebasestorage.app',
    iosBundleId: 'com.example.bookshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFN1uy0IcQ8flDOndS2uYWs5cNJZZbkP4',
    appId: '1:748792057873:web:c32c579f4c50ee7e5021b0',
    messagingSenderId: '748792057873',
    projectId: 'propopo-bookshelf',
    authDomain: 'propopo-bookshelf.firebaseapp.com',
    storageBucket: 'propopo-bookshelf.firebasestorage.app',
  );
}
